// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG9q2L7dsJ4uf98yhfUeC80-H0op_YHPg',
    appId: '1:424310445214:web:3a5a75580d1304a773178f',
    messagingSenderId: '424310445214',
    projectId: 'meal-app-759e8',
    authDomain: 'meal-app-759e8.firebaseapp.com',
    storageBucket: 'meal-app-759e8.appspot.com',
    measurementId: 'G-KBK6TDYKK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDricfNjDsS1bbZTbY8nXgVTLxAgE1UIaE',
    appId: '1:424310445214:android:d2f2d79cd0063e9a73178f',
    messagingSenderId: '424310445214',
    projectId: 'meal-app-759e8',
    storageBucket: 'meal-app-759e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeBgyO1yYDBO-UZmjW6S6LBAMh1lkAr-g',
    appId: '1:424310445214:ios:882da15236cc9adc73178f',
    messagingSenderId: '424310445214',
    projectId: 'meal-app-759e8',
    storageBucket: 'meal-app-759e8.appspot.com',
    iosClientId: '424310445214-mucatg3h7jj003h6ist6c7egc1a8mhsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealpp',
  );
}
